### PR TITLE
G1 s3.filter expense based on budget category

### PR DESCRIPTION
**Pull request by AhmadALshalabi**
Suggestion to merge to branch "group1-sprint3" 
The branch is filter to list all expenses to respective budget and category by specific userId 
need to be reviewed and confirmed please 🙏

### CODE REVIEW

**Review by Bergewing — APPROVED** [review]
I can't see any problems here, I am curious on what problem you discovered last night though!

**Comment by Krezeb** [comment]
Ser bra ut.

**Review by Krezeb — APPROVED** [review]
Ser bra ut. Inga merge Conflicts och är namngivit så man förstår vad som händer med en blick.

**Review by Saru444 — APPROVED** [review]
fint

**Pull request merged**
